version: '3'

name: getting-started-with-lucky

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:30401
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: host

  postgres:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - 30402:5432
    volumes:
      - ../tmp/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
